### ISSUE TITLE
Fails to build on Ubuntu 18.10 for me:

### ISSUE THREAD

**Issue by alexmyczko** [reduz/zytrax#2]
```
g++ -o bin/sytrax.o -c -g3 -pthread -Iglobals -Igui -I. -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/lilv-0 -I/usr/include/sratom-0 -I/usr/include/sord-0 -I/usr/include/serd-0 -I/usr/include/suil-0 bin/sytrax.cpp
In file included from bin/sytrax.cpp:3:
./drivers/audio_effect_factory_lv2.h:17:2: error: 'LV2_Evbuf' does not name a type
  LV2_Evbuf* evbuf;
  ^~~~~~~~~
scons: *** [bin/sytrax.o] Error 1
scons: building terminated because of errors.
make: *** [Makefile:2: all] Error 2
```

I get it, this is only for Windows, right?

**Comment by ngeiswei** [comment]
I don't have this error (on Ubuntu 18.10 as well), I suppose it's been fixed by now.

**Comment by alexmyczko** [comment]
Can confirm builds now! however being remotely on a machine I had to run it like this:

`XDG_CURRENT_DESKTOP=bobmarley scons`
